language: dart
dart:
  # Any version is cool but use stable.
  - stable
# Explicit build lifecycle
install:
  - pub --verbosity=normal get
before_script:
  - pub --verbosity=normal build
script:
  - pub --verbosity=all run test