# Copyright (c) 2015, Steven Bennett.  All rights reserved.  Please see the
# AUTHORS file for collaborators. This code is distributed with a copy of
# the MIT license.  Please see the LICENSE file for details and rights.

# Travis CI Build Instructions.
# Build Dart project, run unit tests, and package an Electron App.

language: dart
dart:
  # Any version is cool but use stable.
  - stable
# Explicit build lifecycle
install:
  # Build script performs pub get and build then adds
  # Electron components into build dir.
  - bash ./scripts/build.sh
before_script:
  # Zip through unit tests now that the project is
  # built.
  - pub --verbosity=all run test
script:
  # Project is built and tests have passed.  Now kick
  # off the packaging script to make an Electron app!
  - bash ./scripts/package_app.sh

