language: dart
dart:
  # Any version is cool but use stable.
  - stable
# Explicit build lifecycle
install:
  - pub --verbosity=normal get
script:
  - pub --verbosity=normal build
after-success:
  - pub --verbosity=all run test