# Copyright (c) 2015, Steven Bennett.  All rights reserved.  Please see the
# AUTHORS file for collaborators. This code is distributed with a copy of
# the MIT license.  Please see the LICENSE file for details and rights.

# Package dependency and information metadata for this pub package.
# https://www.dartlang.org/tools/pub/pubspec.html

name: novella
version: 0.0.10
description: An open-source eBook manager built with web technologies.
author: Steven Bennett <stevebennett08@gmail.com>
homepage: https://github.com/spbennett/novella
documentation: https://github.com/spbennett/novella/wiki
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  args: ^0.13.0
  browser: any
  core_elements: ^0.7.0
  lawndart: ^0.9.0
  paper_elements: ^0.7.0
  polymer: ^0.16.0
  route_hierarchical: ^0.6.0
  yaml: ^2.1.0
dev_dependencies:
  test: ^0.12.0
transformers:
  - polymer:
      entry_points: web/index.html
executables:
  jsonGenerator: jsonGenerator
